
# Creates automatically menu items depending on "content/<directory>"
# sectionPagesMenu = "main"

theme = 'sohakenTheme'

summaryLength = 70

defaultContentLanguage = 'ja'

staticDir = 'static'

[params]
    mainSections = ['seminars', 'news'] # section names displayed in Home page
    paginate = 10 # the number of items diplayed in Home page

[languages] # This will sort though all our language options and keep things neat
    [languages.ja] # the URL for japanese pages will be ~/
        baseURL = "/"
        languageName = '日本語'
        languageCode = 'ja'
        title = '広島大学｜素粒子ハドロン理論'
        weight = 1 # Keeps japanese as the most important
        [languages.ja.Menu]
            [[languages.ja.Menu.main]]
                name = "ホーム"
                url = "/"
                weight = 1
            [[languages.ja.Menu.main]]
                name = "メンバー"
                url = "/members/"
                weight = 2
            [[languages.ja.Menu.main]]
                name = "セミナー"
                url = "/seminars/"
                weight = 3
            [[languages.ja.Menu.main]]
                name = "出来事"
                url = "/news/"
                weight = 4
            [[languages.ja.Menu.main]]
                name = "アクセス"
                url = "/access/"
                weight = 5
    [languages.en]  # the URL for english pages will be ~/en
        baseURL = "/"
        languageName = 'English'
        languageCode = 'en-us'
        title = 'Hiroshima Univ. Particles and Hardon'
        weight = 2
        [languages.en.Menu]
            [[languages.en.Menu.main]]
                name = "Home"
                url = "/"
                weight = 1
            [[languages.en.Menu.main]]
                name = "Members"
                url = "/members/"
                weight = 2
            [[languages.en.Menu.main]]
                name = "Seminars"
                url = "/seminars/"
                weight = 3
            [[languages.en.Menu.main]]
                name = "News"
                url = "/news/"
                weight = 4
            [[languages.en.Menu.main]]
                name = "Access"
                url = "/access/"
                weight = 5
